#  Copyright (c) Code Written and Tested by Ahmed Emad in 14/02/2020, 17:57

# Generated by Django 3.0.3 on 2020-02-14 15:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(null=True, upload_to=users.models.photo_upload)),
                ('phone_number', models.BigIntegerField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                                 to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('H', 'House'), ('O', 'Office'), ('A', 'Apartment')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('apartment_no', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField(blank=True)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9,
                                                           validators=[django.core.validators.MaxValueValidator(180),
                                                                       django.core.validators.MinValueValidator(
                                                                           -180)])),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9,
                                                          validators=[django.core.validators.MaxValueValidator(90),
                                                                      django.core.validators.MinValueValidator(-90)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses',
                                           to='users.UserProfileModel')),
            ],
            options={
                'ordering': ['sort'],
                'unique_together': {('user', 'sort')},
            },
        ),
    ]
