# Generated by Django 3.0 on 2019-12-16 14:27

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0003_auto_20191216_1427'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='land_line_number',
        ),
        migrations.RemoveField(
            model_name='useraddressmodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='favourite_products',
            field=models.ManyToManyField(to='shops.ProductModel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=users.models.photo_upload),
        ),
    ]
