#  Copyright (c) Code Written and Tested by Ahmed Emad on 2019

# Generated by Django 3.0 on 2019-12-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20191216_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
