# Generated by Django 3.0 on 2019-12-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191225_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='user',
            new_name='account',
        ),
    ]
