# Generated by Django 3.0 on 2019-12-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191228_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddressmodel',
            options={'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='sort',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useraddressmodel',
            unique_together={('user', 'sort')},
        ),
    ]
