# Generated by Django 3.0 on 2019-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191229_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddressmodel',
            name='type',
            field=models.CharField(choices=[('H', 'House'), ('O', 'Office'), ('A', 'Apartment')], max_length=1),
        ),
    ]
