# Generated by Django 3.0 on 2019-12-31 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191231_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='favourite_products',
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='useraddressmodel',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
