# Generated by Django 3.0 on 2020-01-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20200104_1657'),
        ('users', '0008_auto_20191231_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='favourite_products',
            field=models.ManyToManyField(to='shops.ProductModel'),
        ),
    ]
