# Generated by Django 3.0 on 2020-01-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofilemodel_favourite_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='favourite_products',
        ),
    ]
