# Generated by Django 3.0 on 2020-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_userprofilemodel_favourite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='phone_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
