#  Copyright (c) Code Written and Tested by Ahmed Emad in 05/02/2020, 00:39

# Generated by Django 3.0.3 on 2020-02-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20200125_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressmodel',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddressmodel',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
