#  Copyright (c) Code Written and Tested by Ahmed Emad in 31/01/2020, 17:29

# Generated by Django 3.0 on 2019-12-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import drivers.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to=drivers.models.photo_upload)),
                ('is_active', models.BooleanField(default=False)),
                ('last_time_online', models.DateTimeField()),
                ('live_location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('live_location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('vehicle_type', models.PositiveIntegerField()),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile',
                                      to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.BigIntegerField(default=0))
            ],
        ),
        migrations.CreateModel(
            name='DriverReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('time_stamp', models.DateTimeField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                             to='drivers.DriverProfileModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='users.UserProfileModel')),
                ('sort', models.PositiveIntegerField(default=1))
            ],
        ),
    ]
