#  Copyright (c) Code Written and Tested by Ahmed Emad in 14/02/2020, 17:57

# Generated by Django 3.0.3 on 2020-02-14 15:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import drivers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to=drivers.models.photo_upload)),
                ('phone_number', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('last_time_online', models.DateTimeField(default=None, null=True)),
                ('live_location_longitude', models.FloatField(default=0,
                                                              validators=[django.core.validators.MaxValueValidator(180),
                                                                          django.core.validators.MinValueValidator(
                                                                              -180)])),
                ('live_location_latitude', models.FloatField(default=0,
                                                             validators=[django.core.validators.MaxValueValidator(90),
                                                                         django.core.validators.MinValueValidator(
                                                                             -90)])),
                ('vehicle_type',
                 models.CharField(choices=[('C', 'Car'), ('M', 'Motorcycle'), ('B', 'Bike')], max_length=1)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('account',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile',
                                      to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverReviewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.PositiveIntegerField()),
                ('stars', models.FloatField(validators=[django.core.validators.MaxValueValidator(5),
                                                        django.core.validators.MinValueValidator(0.5)])),
                ('text', models.TextField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews',
                                             to='drivers.DriverProfileModel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='users.UserProfileModel')),
            ],
            options={
                'ordering': ['sort'],
                'unique_together': {('driver', 'sort')},
            },
        ),
    ]
