# Generated by Django 3.0 on 2019-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20191230_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='vehicle_type',
            field=models.CharField(choices=[('C', 'Car'), ('M', 'Motorcycle'), ('B', 'Bike')], max_length=1),
        ),
    ]
