# Generated by Django 3.0 on 2019-12-31 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20191231_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='live_location_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='live_location_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
