# Generated by Django 3.0 on 2020-01-02 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_auto_20191231_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='driverreviewmodel',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
