#  Copyright (c) Code Written and Tested by Ahmed Emad in 29/01/2020, 21:31

# Generated by Django 3.0 on 2020-01-25 19:06

from django.db import migrations, models
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_auto_20200102_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=drivers.models.photo_upload),
            preserve_default=False,
        ),
    ]
