#  Copyright (c) Code Written and Tested by Ahmed Emad in 05/02/2020, 20:26

# Generated by Django 3.0.3 on 2020-02-05 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drivers', '0011_auto_20200131_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofilemodel',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='live_location_latitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(90),
                                                           django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='live_location_longitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180),
                                                           django.core.validators.MinValueValidator(-180)]),
        ),
    ]
