#  Copyright (c) Code Written and Tested by Ahmed Emad in 06/02/2020, 16:49

# Generated by Django 3.0.3 on 2020-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('drivers', '0012_auto_20200205_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofilemodel',
            name='last_time_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
