# Generated by Django 3.0 on 2019-12-08 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to=accounts.models.photo_upload)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=15)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('apartment_no', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('land_line_number', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses',
                                           to='accounts.UserProfileModel')),
            ],
        ),
    ]
