# Generated by Django 3.0 on 2019-12-09 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('changes_price', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                                   to='shops.OptionGroupModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='addon',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='currency',
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='currency',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='minimum_charge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RelyOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='rely_ons', to='shops.AddOn')),
                ('choosed_option_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionGroupModel')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionModel')),
                ('option_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   related_name='rely_ons', to='shops.OptionGroupModel')),
            ],
        ),
        migrations.AddField(
            model_name='optiongroupmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups',
                                    to='shops.ProductModel'),
        ),
    ]
