# Generated by Django 3.0 on 2019-12-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_auto_20191209_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoryModel',
            new_name='ProductGroupModel',
        ),
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='optiongroupmodel',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='optionmodel',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='productgroupmodel',
            options={'ordering': ['sort']},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
        migrations.RemoveField(
            model_name='relyon',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='shopaddressmodel',
            name='land_line_number',
        ),
        migrations.RemoveField(
            model_name='shopaddressmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='shopprofilemodel',
            name='favourite_user',
        ),
        migrations.AddField(
            model_name='addon',
            name='sort',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optiongroupmodel',
            name='sort',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionmodel',
            name='sort',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                    to='shops.ProductGroupModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='delivery_fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='phone_number',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='vat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='choosed_option_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionGroupModel'),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionModel'),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='option_group',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='rely_on', to='shops.OptionGroupModel'),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='minimum_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shopreviewmodel',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='addon',
            unique_together={('product', 'sort')},
        ),
        migrations.AlterUniqueTogether(
            name='optiongroupmodel',
            unique_together={('product', 'sort')},
        ),
        migrations.AlterUniqueTogether(
            name='optionmodel',
            unique_together={('option_group', 'sort')},
        ),
    ]
