# Generated by Django 3.0 on 2019-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0003_auto_20191216_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
