# Generated by Django 3.0 on 2019-12-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0004_productmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofilemodel',
            name='closes_at',
            field=models.TimeField(auto_now=False, auto_now_add=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='opens_at',
            field=models.TimeField(auto_now=False, auto_now_add=False),
            preserve_default=False,
        ),
    ]
