# Generated by Django 2.2.7 on 2019-12-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0005_auto_20191217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relyon',
            name='choosed_option_group',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='relyon',
            name='option',
            field=models.SmallIntegerField(default=1),
        ),
    ]
