# Generated by Django 3.0 on 2019-12-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20191225_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='shop_type',
            field=models.CharField(choices=[('F', 'Food'), ('G', 'Groceries'), ('P', 'Pharmacy')], max_length=1),
        ),
    ]
