# Generated by Django 3.0 on 2020-01-04 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20191231_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='productreviewmodel',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('egp', 'Egyptian Pound')], max_length=3),
        ),
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='shopreviewmodel',
            name='stars',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
