# Generated by Django 3.0 on 2020-01-05 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20200104_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviewmodel',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='shopreviewmodel',
            options={'ordering': ['sort']},
        ),
        migrations.RenameField(
            model_name='shopprofilemodel',
            old_name='user',
            new_name='account',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='shop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.ShopProfileModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreviewmodel',
            name='sort',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopprofilemodel',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopreviewmodel',
            name='sort',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='productmodel',
            unique_together={('shop', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='productreviewmodel',
            unique_together={('product', 'sort')},
        ),
        migrations.AlterUniqueTogether(
            name='shopreviewmodel',
            unique_together={('shop', 'sort')},
        ),
        migrations.RemoveField(
            model_name='productreviewmodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shopreviewmodel',
            name='title',
        ),
    ]
