# Generated by Django 3.0 on 2020-01-06 11:27

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20200105_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=shops.models.shop_photo_upload),
        ),
    ]
