# Generated by Django 3.0 on 2020-01-09 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20200108_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relyon',
            name='option_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rely_ons', to='shops.OptionGroupModel'),
        ),
    ]
