# Generated by Django 3.0 on 2020-01-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20200109_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionmodel',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
