# Generated by Django 3.0 on 2020-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0017_auto_20200110_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='num_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
