# Generated by Django 3.0 on 2020-01-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_productmodel_num_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.ProductGroupModel'),
        ),
    ]
