# Generated by Django 3.0 on 2020-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20200119_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonmodel',
            name='sort',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
