# Generated by Django 3.0 on 2020-01-25 19:06

from django.db import migrations, models
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_auto_20200121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofilemodel',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to=shops.models.shop_photo_upload),
            preserve_default=False,
        ),
    ]
