# Generated by Django 3.0 on 2020-01-26 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0023_auto_20200125_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='location_latitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='shopaddressmodel',
            name='location_longitude',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)]),
        ),
    ]
