#  Copyright (c) Code Written and Tested by Ahmed Emad in 31/01/2020, 17:29

# Generated by Django 3.0 on 2020-01-31 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0024_auto_20200126_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofilemodel',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=[''],
                                                            size=3),
            preserve_default=False,
        ),
    ]
