#  Copyright (c) Code Written and Tested by Ahmed Emad in 31/01/2020, 17:29

# Generated by Django 3.0 on 2020-01-31 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0025_shopprofilemodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofilemodel',
            name='tags',
        ),
        migrations.CreateModel(
            name='ShopTagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags',
                                           to='shops.ShopProfileModel')),
            ],
        ),
    ]
