#  Copyright (c) Code Written and Tested by Ahmed Emad in 01/02/2020, 18:18

# Generated by Django 3.0 on 2020-02-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0028_auto_20200131_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofilemodel',
            name='time_to_prepare',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
