#  Copyright (c) Code Written and Tested by Ahmed Emad in 01/02/2020, 18:18

# Generated by Django 3.0 on 2020-02-01 14:01

from django.db import migrations, models

import shops.models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0029_shopprofilemodel_time_to_prepare'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofilemodel',
            name='cover_photo',
            field=models.ImageField(default='', upload_to=shops.models.shop_photo_upload),
            preserve_default=False,
        ),
    ]
