#  Copyright (c) Code Written and Tested by Ahmed Emad in 21/02/2020, 20:11

# Generated by Django 3.0.3 on 2020-02-21 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('shops', '__first__'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('H', 'House'), ('O', 'Office'), ('A', 'Apartment')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('apartment_no', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField(blank=True)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9,
                                                           validators=[django.core.validators.MaxValueValidator(180),
                                                                       django.core.validators.MinValueValidator(
                                                                           -180)])),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9,
                                                          validators=[django.core.validators.MaxValueValidator(90),
                                                                      django.core.validators.MinValueValidator(-90)])),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('status',
                 models.CharField(choices=[('C', 'confirmed'), ('P', 'picked'), ('D', 'delivered')], default='C',
                                  max_length=2)),
                ('final_price', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('vat', models.FloatField()),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='served_orders', to='drivers.DriverProfileModel')),
                ('shipping_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                          to='orders.OrderAddressModel')),
                ('shops', models.ManyToManyField(related_name='served_orders', to='shops.ShopProfileModel')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders',
                                   to='users.UserProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemsGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_groups',
                                   to='orders.OrderModel')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='shops.ShopProfileModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('special_request', models.TextField(blank=True)),
                ('price', models.FloatField(default=0)),
                ('add_ons', models.ManyToManyField(to='shops.AddOnModel')),
                ('item_group',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                   to='orders.OrderItemsGroupModel')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosed_option',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.OptionModel')),
                ('option_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                   to='shops.OptionGroupModel')),
                ('order_item',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices',
                                   to='orders.OrderItemModel')),
            ],
        ),
    ]
