# Generated by Django 3.0 on 2019-12-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('drivers', '__first__'),
        ('users', '__first__'),
        ('shops', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField()),
                ('arrived', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='served_orders', to='drivers.DriverProfileModel')),
                ('shipping_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                          to='users.UserAddressModel')),
                ('shops', models.ManyToManyField(related_name='served_orders', to='shops.ShopProfileModel')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders',
                                   to='users.UserProfileModel')),
            ],
        ),
    ]
