# Generated by Django 3.0 on 2019-12-09 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_auto_20191209_1846'),
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='accounts.UserAddressModel'),
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('add_ons', models.ManyToManyField(to='shops.AddOn')),
                ('option_groups', models.ManyToManyField(to='shops.OptionGroupModel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                            to='orders.OrderModel')),
                ('product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.ProductModel')),
            ],
        ),
    ]
