#  Copyright (c) Code Written and Tested by Ahmed Emad in 21/02/2020, 20:11

# Generated by Django 3.0.3 on 2020-02-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_shopprofilemodel_cover_photo'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='add_ons',
            field=models.ManyToManyField(null=True, to='shops.AddOnModel'),
        ),
    ]
