# Generated by Django 3.0 on 2019-12-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0002_auto_20191209_1846'),
        ('orders', '0002_auto_20191209_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='option_groups',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='final_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choosed_option',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionModel')),
                ('option_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionGroupModel')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices',
                                                 to='orders.OrderItemModel')),
            ],
        ),
    ]
