# Generated by Django 3.0 on 2019-12-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_auto_20191209_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='special_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='vat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
