#  Copyright (c) Code Written and Tested by Ahmed Emad in 21/02/2020, 20:11

# Generated by Django 3.0.3 on 2020-02-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0003_auto_20200221_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order',
                                       to='orders.OrderAddressModel'),
        ),
    ]
