# Generated by Django 3.0 on 2019-12-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0004_auto_20191216_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choosed_option',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option_group',
            field=models.SmallIntegerField(default=1),
        ),
    ]
