#  Copyright (c) Code Written and Tested by Ahmed Emad on 2019

# Generated by Django 3.0 on 2019-12-25 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shops', '0007_auto_20191225_1814'),
        ('orders', '0005_auto_20191217_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choosed_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionModel'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.OptionGroupModel'),
        ),
    ]
