# Generated by Django 3.0 on 2020-01-15 20:29
import datetime

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_productmodel_num_sold'),
        ('orders', '0006_auto_20191225_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('H', 'House'), ('O', 'Office'), ('A', 'Apartment')], max_length=1)),
                ('street', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('apartment_no', models.PositiveIntegerField(default=1)),
                ('special_notes', models.TextField(blank=True)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choosed_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.OptionModel'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='option_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.OptionGroupModel'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='orders.OrderItemModel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='vat',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='OrderItemsGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.ShopProfileModel')),
            ],
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='item_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.OrderItemsGroupModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.OrderAddressModel'),
        ),
    ]
