# Generated by Django 3.0 on 2020-01-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200115_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsgroupmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.OrderModel'),
        ),
    ]
