# Generated by Django 3.0 on 2020-01-16 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsgroupmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_groups', to='orders.OrderModel'),
        ),
    ]
