# Generated by Django 3.0 on 2020-01-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_productmodel_num_sold'),
        ('orders', '0009_auto_20200116_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemsgroupmodel',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='orders.OrderModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemsgroupmodel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.ShopProfileModel'),
        ),
    ]
