# Generated by Django 3.0 on 2020-01-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.OrderItemsGroupModel'),
        ),
    ]
