# Generated by Django 3.0 on 2020-01-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200117_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsgroupmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='orders.OrderModel'),
        ),
    ]
