# Generated by Django 3.0 on 2020-01-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200117_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='product',
            new_name='ordered_product',
        ),
    ]
