# Generated by Django 3.0 on 2020-01-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200119_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='ordered_product',
            new_name='product',
        ),
    ]
