# Generated by Django 3.0 on 2020-01-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200119_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('C', 'confirmed'), ('PR', 'preparing'), ('PI', 'picked'), ('D', 'delivered')], default='C', max_length=2),
        ),
    ]
