# Generated by Django 3.0 on 2020-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('C', 'confirmed'), ('P', 'picked'), ('D', 'delivered')], default='C', max_length=2),
        ),
    ]
